version: 2

models:
  - name: base_useroperations
    data_tests:
      - dbt_utils.unique_combination_of_columns:
          arguments:
            combination_of_columns:
              - block_date
              - op_hash
    columns:
      - name: block_date
        tests:
          - not_null
      - name: op_hash
        tests:
          - not_null
  - name: uo_builder_codes
    data_tests:
      - dbt_utils.unique_combination_of_columns:
          arguments:
            combination_of_columns:
              - block_date
              - unique_id
    columns:
      - name: block_date
        tests:
          - not_null
      - name: unique_id
        tests:
          - not_null
  - name: tx_builder_codes
    data_tests:
      - dbt_utils.unique_combination_of_columns:
          arguments:
            combination_of_columns:
              - block_date
              - unique_id
    columns:
      - name: block_date
        tests:
          - not_null
      - name: unique_id
        tests:
          - not_null
  - name: builder_code_metrics
    data_tests:
      - dbt_utils.unique_combination_of_columns:
          arguments:
            combination_of_columns:
              - block_date
              - builder_code
    columns:
      - name: block_date
        tests:
          - not_null
      - name: builder_code
        tests:
          - not_null
